services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    platform: linux/amd64
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      MSSQL_PID: ${MSSQL_PID}
    volumes:
      - mssql-data:/var/opt/mssql
      - ./scripts/init_instnwnd.sh:/init/init_instnwnd.sh
      - ./sql/instnwnd.sql:/init/instnwnd.sql
    command: /bin/bash /init/init_instnwnd.sh 

volumes:
  mssql-data: